Added basic Twilio send wrapper and receive message controller
uwblueprint/somo pull request #31
Opened 2016-11-02 00:24 UTC by chrisjluc

Issue: https://github.com/uwblueprint/somo/issues/14

Need somewhere to store our confidential tokens and credentials... any suggestions?

2016-11-08 22:56 UTC, MKhowaja commented on lib/sms/client.rb
> +    somo_phone_number = '437-800-2780'
Probably consider extracting these constants to a config file and perhaps encrypting them with a hash

2016-11-08 22:58 UTC, MKhowaja requested changes
Encrypt the constants in a file with a hash
Test the send method when the server is up

2016-11-09 06:11 UTC, chrisjluc commented
@MKhowaja Didn't encrypt the file, think that's too much for our current state, i put it in the `secrets.yml`. Tested by running a script that instantiates the class and successfully sends a message.

2016-11-09 18:46 UTC, MKhowaja approved these changes

2016-11-09 19:43 UTC, merged